server:
    applicationConnectors:
        - type: http
          port: 3000
    adminConnectors:
        - type: http
          port: 3001

logging:
  #It can take values: OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  #INFO is default level of all loggers.
  level: INFO


question: "What should I call you?"

greetingTemplate: "Hello, %s!!"
